- README.md
> fix links and add package name

- example/dock-did.js
- package.json
- src/api.js
- src/utils/codec.js
- src/utils/misc.js
- src/utils/revocation/did-keys.js
- src/utils/revocation/one-of-policy.js
- src/utils/vc.js
- src/verifiable-credential.js
- src/verifiable-presentation.js
- tests/integration/issuing.test.js
- tests/unit/issuing.test.js
- tests/unit/utils.test.js
- tsconfig.json
- yarn.lock
Helps to address https://github.com/docknetwork/sdk/issues/89
> Type check tests and example scripts

- scripts/config
> CI will pull docker image for develop branch of node

- example/standard_schemas.js
- src/modules/schema.js
- src/utils/vc/schemas/bol.js
- src/utils/vc/schemas/health_worker_passport.js
- src/utils/vc/schemas/immunity_event_record.js
- src/utils/vc/schemas/infection_diagnosis.js
- src/utils/vc/schemas/non_infection_check.js
- src/utils/vc/schemas/pr_card.js
- src/utils/vc/schemas/proof_of_health_core.js
- src/utils/vc/schemas/qp_inbond.js
> Add example scripts for schema

- src/modules/blob.js
- tutorials/src/schemas.md
Solves https://dock-team.atlassian.net/browse/DCK-30
> Tutorial on blobs and schemas.

- example/resolver.js
- src/modules/schema.js
- src/verifiable-credential.js
- src/verifiable-presentation.js
- tests/unit/serialize.test.js
Fixes https://github.com/docknetwork/sdk/issues/73
> Serialize tests [Jira: DCK-79]

- package.json
- src/utils/revocation/keyring-pair-did-keys.js
- src/utils/revocation/one-of-policy.js
- tests/integration/revocation.test.js
- yarn.lock
Fixes https://github.com/docknetwork/sdk/issues/125
> Unskip and fix "Can create a registry with multiple controllers" test [Jira: DCK-83]

- src/utils/type-helpers.js
- src/verifiable-credential.js
- src/verifiable-presentation.js
- tests/unit/issuing.test.js
- tutorials/src/tutorial_ipv.md
Fixes https://github.com/docknetwork/sdk/issues/75
> Dont enforce requirement of @context key in object when setting VP/VC contexts [Jira: DCK-80]

- package.json
- scripts/get_did_doc.js
> Script to get the DID doc for a DID

- example/standard_schemas.js
- package.json
- src/utils/vc.js
- src/verifiable-credential.js
- tests/example-credential.js
- tests/integration/credential-revocation.test.js
- tests/integration/schema.test.js
- tests/unit/cred-revocation.test.js
- tests/unit/schema.test.js
- yarn.lock
Helps to address some concerns in https://github.com/docknetwork/sdk/issues/59
> Refactor vc.js methods to use expanded credentials and presentations

- example/revocation.js
minor cleanup to avoid confusion
> Remove unused revokeIds var from revocation example

- example/blob.js
- src/modules/blob.js
- src/modules/schema.js
- tests/integration/blob.test.js
Also should try to auto detect input type in get method, eg: passing json will result in json from get method without need for user to parse it
> Update blob module to auto detect value type so user doesnt need to import helper methods

- tests/integration/master.test.js
@lovesh 
This is the check you requested at today's PM meeting. It calls a root function other than `system::set_storage` as master. The function it calls is `master::set_members`.
I made it an integration test because why not.
> Additional master test

- example/create_master_proposal.js
This is an example of how to create an on-chain "Call", json encoded for use in master voting.
> Create proposal example

- package.json
- rollup.config.js
- yarn.lock
also added temporarily-disabled rollup WASM plugin (see comments in rollup onfig)
> Add rify package, upgrade rollup

- README.md
- env_example
- package.json
- scripts/epoch_detail.js
- scripts/get_session_keys.js
- scripts/get_summary.js
- scripts/helpers.js
- src/utils/codec.js
> Allow addresses to be generated for network

- .github/workflows/run-examples.yml
Should help speed up CI a little
> Split examples workflow from tests

- package.json
- tests/integration/issuing.test.js
- tests/mocks/axios.js
- tests/network-cache.js
- tests/unit/issuing.test.js
- tsconfig.json
Resolves https://github.com/docknetwork/sdk/issues/176
> Mock axios in issuing test

- example/chain-ops.js
- src/utils/chain-ops.js
> add another method

- package.json
- tests/unit/claim-deduction.test.js
- yarn.lock
Resolves https://github.com/docknetwork/sdk/issues/197
> Upgrade to latest JSON-LD and signatures package versions

- package.json
- scripts/helpers.js
- src/modules/migration.js
- tests/poa/token_migration.test.js
> Fix `migrateRecipAsList` for repeated address

- tutorials/src/SUMMARY.md
- tutorials/src/concepts_poe_anchors.md
- tutorials/src/tutorial_poe_anchors.md
This is ready for review ~but it branches of of `anchoring-example` so we should wait for #204 to be merged before merging this.~
~Commit cc035e1 is the only change.~
> Anchoring docs

- src/utils/claimgraph.js
- tests/unit/claimgraph.test.js
> language tagged string equality

- package.json
this pr only bumps the version in package.json `0.3.11 -> 0.3.12`
> version 0.3.12

- package.json
- yarn.lock
Resolves a dependabot security issue
> Pin axios version

- src/rdf-defs.js
- tests/cached-document-loader.js
- tests/unit/claim-deduction.test.js
- tests/unit/logic.test.js
Blocked by #231
Don't merge this directly. The target of this pr is `quads` but it should be changed to `master` before merging.
> Private delegation logic

- tutorials/src/SUMMARY.md
- tutorials/src/concepts_private_delegation.md
- tutorials/src/concepts_vcdm.md
- tutorials/src/tutorial_poe_anchors.md
- tutorials/src/tutorial_private_delegation.md
rendered
- https://github.com/docknetwork/sdk/blob/private-delegation-tuts/tutorials/src/concepts_private_delegation.md
- https://github.com/docknetwork/sdk/blob/private-delegation-tuts/tutorials/src/tutorial_private_delegation.md
> Private delegation concepts and tutorial

- scripts/config
- src/modules/did.js
- src/types.json
- src/utils/did.js
- tests/integration/did.test.js
Waiting on mainnet changes before we can merge this
> DID Attestations

- src/signatures/signature-secp256k1.js
- src/utils/misc.js
- tests/integration/did.test.js
- tests/integration/issuing.test.js
- tests/integration/presenting.test.js
- tests/network-cache.js
- tests/unit/issuing.test.js
- tests/unit/utils.test.js
> Hash message before signing in ECDSA

- package.json
- src/utils/misc.js
- src/utils/vc/crypto/EcdsaSecp256k1VerificationKey2019.js
- yarn.lock
latest nextjs had build errors with how we imported elliptic
> fix elliptic import build errors

- package.json
- src/universal-resolver.js
- src/utils/vc/crypto/EcdsaSecp256k1VerificationKey2019.js
- src/utils/vc/crypto/Ed25519VerificationKey2018.js
- src/utils/vc/crypto/Sr25519VerificationKey2020.js
- yarn.lock
Related issue: https://github.com/docknetwork/vcdm-verifier/issues/35
> Fix universal resolver and wider key type encoding support

- example/didweb.js
- package.json
- src/universal-resolver.js
- src/utils/vc/contexts.js
- src/utils/vc/crypto/EcdsaSecp256k1VerificationKey2019.js
- src/utils/vc/crypto/Ed25519VerificationKey2018.js
- src/utils/vc/crypto/Sr25519VerificationKey2020.js
- yarn.lock
Thought it prudent to have a clear example of a non dock did credential being verified. Also found some issues that seem to have been resolved by upgrading jsonld-signatures to 9.0.0
> Verification fixes, didweb example

- package.json
- src/utils/vc/contexts/dock-bbs-v1.json
- src/utils/vc/contexts/dock-bbs23-v1.json
- src/utils/vc/contexts/dock-ps-v1.json
- yarn.lock
> Upgrade crypto-wasm-ts to 0.41.0

- package.json
- src/modules/trust-registry.js
- src/public-keys/public-key.js
- src/resolver/did/did-resolver.js
- src/utils/codec.js
- src/utils/did.js
- tests/integration/did/did-key.test.js
- tests/unit/did.test.js
did:key currently encodes as SS58 - this is incorrect. this PR should address that
> Fix did:key incorrect encoding

- .github/workflows/npm-audit.yml
Finally getting around to rolling out the license checking action to other repos
> adding action for checking licenses

- package.json
- src/utils/vc/crypto/common/DockCryptoSignature.js
- tests/integration/anoncreds/demo.test.js
- tests/integration/anoncreds/r1cs-circom.test.js
- tests/integration/anoncreds/saver-and-bound-check.test.js
- yarn.lock
Reverts docknetwork/sdk#445
Needs investigating why the older anoncreds (KVAC) credentials failed to verify after this change
> Revert "Revert anoncreds upgrade"

- LICENSE.md
- packages/cheqd-blockchain-api/LICENSE
- packages/cheqd-blockchain-modules/LICENSE
- packages/credential-sdk/LICENSE
- packages/dock-blockchain-api/LICENSE
- packages/dock-blockchain-modules/LICENSE
Root license file + licenses for each package just to be clear. All MIT
> Restore licenses

- examples/CHANGELOG.md
- examples/package.json
- package.json
- packages/cheqd-blockchain-api/CHANGELOG.md
- packages/cheqd-blockchain-api/package.json
- packages/cheqd-blockchain-modules/CHANGELOG.md
- packages/cheqd-blockchain-modules/package.json
- packages/credential-sdk/CHANGELOG.md
- packages/credential-sdk/package.json
- packages/credential-sdk/src/rdf-and-cd/rdf.js
- packages/credential-sdk/tests/crawl.test.js
- packages/credential-sdk/tests/rdf-turtle.test.js
- packages/dock-blockchain-api/CHANGELOG.md
- packages/dock-blockchain-api/package.json
- packages/dock-blockchain-modules/CHANGELOG.md
- packages/dock-blockchain-modules/package.json
- yarn.lock
Resolves some package audit issues
> Audit fixes, RDF library upgrade

- examples/CHANGELOG.md
- examples/package.json
- packages/credential-sdk/CHANGELOG.md
- packages/credential-sdk/package.json
- packages/credential-sdk/src/types/did/document/verification-method-ref.js
- scripts/bench/CHANGELOG.md
- scripts/bench/package.json
Allows to use key-1, keys-1 etc
> Support various key identifiers
