- .github/workflows/npm-publish.yml
- package.json
- rollup.config.js
1. Import from src directory so when importing user doesnt need to prepend /src/ to paths
2. Rollup directly into index.*.js in src directory
3. Build before package publish not on pull (yarn prepare script)
4. Remove dist directory
> Refactor SDK import and build process

- package.json
- rollup.config.js
NextJS for example has issues using mjs files that import other modules in the node_modules directory. Webpack in general doesnt seem to be able to resolve importing non-ES modules from ES code as well as node itself can.
> Disable MJS build temporarily as it has issues in certain web build systems

- scripts/config
- src/types.json
- tests/integration/master.test.js
- yarn.lock
This pr introduces integration tests for the Master module on the node. The tests are intended to be run against node at the head of `poa-1` in the dock-sdk repo: e4c5e318cd78d58a4af8de8907e4d90705138b66.
As mentioned in the comment below, this branch should be rebased onto `poa-1` of this repo. TODO
This branch has failing tests and lints but not related to the changes introduced. I think those failing tests and lints should be fixed separately, after merging.
You'll notice `master.test.js` does not use functions exported by the sdk.
> exercise Master functionality from client

- scripts/change_did_key.js
Adds a script to update your own did key. This is needed in order to update the keys of master members on the vulcan testnet.
To save time I didn't add any argument parsing. Users will need to edit this script manually for now.
edit: I added argument parsing.
> implement keyupdate script

- example/standard_schemas.js
- package.json
- src/utils/vc.js
- yarn.lock
also removes some old schema/credentials that don't parse as valid JSON-LD (assuming due to incorrect urls) causing examples to fail
> Fix jsonld-signature and jsonld dependency issues

- .github/workflows/docs.yml
Why? Because of this: https://github.com/docknetwork/sdk/runs/1427368060?check_suite_focus=true
> update ssh agent github action to latest

- src/verifiable-credential.js
- tests/unit/issuing.test.js
It should be upto the creator to determine if ID is required or if they want to use other identifiable data in subject
> Remove requirement for ID field to exist on credentialSubject in addSubject method

- tutorials/src/concepts_vcdm.md
- tutorials/src/tutorial_did.md
- tutorials/src/tutorial_ipv.md
- tutorials/src/tutorial_resolver.md
When I was reading the documentation I found it very hard for my eyes to scan the text, this PR fixes some of that.
For example, I changed:
to:
> Documentation legibility fixes

- package.json
- src/utils/vc/crypto/custom-linkeddatasignature.js
experienced nextjs compile errors with default config due to how we import jsonld-signatures, as theres an issue with that lib:
```
error - SyntaxError: Named export 'suites' not found. The requested module 'jsonld-signatures' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```
> refactor jsonld-signatures import to prevent compile errors downstream

- package.json
- src/utils/vc/credentials.js
- src/utils/vc/document-loader.js
- src/utils/vc/schema.js
- tests/integration/anoncreds/issuing.test.js
BBS+ credential verification was failing if schema resolution was enabled, have updated schema resolution to use the document loader which now supports embedded JSON
> Fix BBS+ verify with schema

- package.json
- src/bbs-plus-presentation.js
- src/utils/vc/contexts/dock-bbs-v1.json
- src/utils/vc/credentials.js
- src/utils/vc/crypto/Bls12381BBSSignatureDock2022.js
- src/utils/vc/crypto/Bls12381BBSSignatureProofDock2022.js
- src/utils/vc/crypto/constants.js
- src/utils/vc/crypto/custom-linkeddatasignature.js
- src/utils/vc/custom_crypto.js
- src/utils/vc/presentations.js
- tests/integration/anoncreds/bbs-derived-credentials.test.js
- tests/integration/anoncreds/bbs-plus-presentation.test.js
- yarn.lock
Since Dock BBS+ presentations are not compatible with W3C verifiable presentations and the specs that rely on it (such as dif pres exchange etc), it makes sense to have a way of deriving a "BBS+ proof" credential that acts the same way. The caveat is that multiple BBS+ credentials derived are not supported this way, but you can always derive from multiple presentations to pack into one W3C Verifiable Presentation.
This is primarily for interop with other libs/systems, and should be the preferable way to use BBS+ credentials and their features within presentations. The basic flow is:
- Use BBS+ presentation builder to select attributes to disclose etc
- Finalize, create BBS+ presentation JSON then convert that to a W3C verifiable credential with BBS+ proof type
- This credential can be …
> Allow to derive BBS+ W3C credentials for presenting

- package.json
- src/utils/vc/contexts.js
- src/utils/vc/contexts/jws-2020-v1.json
- src/utils/vc/credentials.js
- src/utils/vc/crypto/JsonWebSignature2020.js
- src/utils/vc/crypto/custom-linkeddatasignature.js
- src/utils/vc/custom_crypto.js
- src/utils/vc/helpers.js
- src/utils/vc/jws.js
- src/utils/vc/presentations.js
- src/verifiable-credential.js
- src/verifiable-presentation.js
- tests/cached-document-loader.js
- tests/network-cache.js
- tests/test-keys.js
- tests/unit/issuing.test.js
- tests/unit/presigned-validation.test.js
- yarn.lock
- Create JWT VC
- Verify JWT VC
- JsonWebKey2020 support (JWT and non-JWT)
- Updates issuance test to cover more key types
- Added test for pre-signed credentials for robustness
JWT VPs not supported in this PR to keep changes minimal
> JWT VCs and JsonWebKey2020 support

- package.json
- scripts/slack.js
- scripts/watch-essential-events.js
- src/modules/did/did.js
- src/status-list-credential/status-list2021-credential.js
- Make `StatusList2021Credential` update atomic, and rollback all modifications made to the underlying decoded status list in case of an invalid index
- Allow the essential notification watcher to use `Slack` hooks 
- Update metadata to be compatible with the latest `dock-substrate`
> Misc tweaks

- package.json
- yarn.lock
Used to be required, doesnt seem to be anymore
> Fix: dont pin all polkadot packages anymore

- .github/workflows/integrations-tests.yml
- package.json
- src/presentation.js
- src/utils/vc/contexts/dock-bbs-v1.json
- src/utils/vc/contexts/dock-bbs23-v1.json
- src/utils/vc/contexts/dock-ps-v1.json
- src/utils/vc/credentials.js
- src/utils/vc/crypto/common/DockCryptoSignatureProof.js
- src/utils/vc/presentations.js
- tests/integration/anoncreds/derived-credentials.test.js
- tests/integration/anoncreds/presentation.test.js
Fixes "bounds" property not being in derived credentials/presentations, allows to pass anoncreds specific verification parameters (predicates etc) in verifyCredential/verifyPresentation methods
> Anoncreds derived bounds check

- package.json
- src/utils/vc/credentials.js
- src/utils/vc/custom_crypto.js
- tests/integration/anoncreds/derived-credentials.test.js
Skip JSON schema validation when verifying derived credentials, as anoncreds will do its own schema checks. This resolves an issue whereby schema validation fails for required fields that are not revealed.
> Skip schema check for anoncreds derived credentials

- example/standard_schemas.js
- src/utils/vc/credentials.js
- src/utils/vc/schema.js
- src/verifiable-credential.js
- tests/unit/schema.test.js
Expanding the credential subject before verification is incorrect because if a field is not defined in the context, it will result in a potentially empty object to validate (or object with that field popped off) which may pass/fail unexpectedly. Also, it prevented verifying subjects with only the ID field since that is popped off.
Cannot see a requirement in the spec to do JSON-LD processing for schema validation. This change also allows validating of JWT-VC schemas when they dont use JSON-LD (no official support for that format yet but it lays some groundwork)
> Fix verifying schema with only ID field in subject, dont expand for schema validation

- package.json
- src/utils/vc/crypto/common/DockCryptoSignature.js
- tests/integration/anoncreds/demo.test.js
- tests/integration/anoncreds/r1cs-circom.test.js
- tests/integration/anoncreds/saver-and-bound-check.test.js
- yarn.lock
Those two commits have broken validation of existing anoncreds credentials, and the wallet cannot verify the newer issued ones. This PR can be reverted once confirmed and a breaking SDK change deployed simultaneously if needed.
> Revert anoncreds upgrade

- examples/CHANGELOG.md
- examples/package.json
- package.json
- packages/cheqd-blockchain-api/CHANGELOG.md
- packages/cheqd-blockchain-api/package.json
- packages/cheqd-blockchain-modules/CHANGELOG.md
- packages/cheqd-blockchain-modules/jest.config.js
- packages/cheqd-blockchain-modules/package.json
- packages/cheqd-blockchain-modules/tests/attest-module.test.js
- packages/cheqd-blockchain-modules/tests/blob-module.test.js
- packages/cheqd-blockchain-modules/tests/constants.js
- packages/cheqd-blockchain-modules/tests/did-module.test.js
- packages/cheqd-blockchain-modules/tests/offchain-signatures-module.test.js
- packages/credential-sdk/CHANGELOG.md
- packages/credential-sdk/package.json
- packages/credential-sdk/src/types/did/onchain/index.js
- packages/dock-blockchain-api/CHANGELOG.md
- packages/dock-blockchain-api/package.json
- packages/dock-blockchain-modules/CHANGELOG.md
- packages/dock-blockchain-modules/package.json
- packages/dock-blockchain-modules/src/accumulator/internal.js
- packages/dock-blockchain-modules/src/common/inject-params.js
- packages/dock-blockchain-modules/src/common/inject-public-keys.js
- packages/dock-blockchain-modules/src/offchain-signatures/internal.js
- packages/dock-blockchain-modules/tests/integration/anoncreds/accumulator.test.js
- packages/dock-blockchain-modules/tests/integration/anoncreds/scheme.test.js
- scripts/with_dock_docker_test_node
Tweaks for `lastPublicKeyId` and `lastParamsId`
> Tweaks for `lastPublicKeyId` and `lastParamsId`

- examples/CHANGELOG.md
- examples/package.json
- packages/cheqd-blockchain-api/CHANGELOG.md
- packages/cheqd-blockchain-api/package.json
- packages/cheqd-blockchain-modules/CHANGELOG.md
- packages/cheqd-blockchain-modules/package.json
- packages/credential-sdk/CHANGELOG.md
- packages/credential-sdk/package.json
- packages/credential-sdk/src/vc/credentials.js
- packages/dock-blockchain-api/CHANGELOG.md
- packages/dock-blockchain-api/package.json
- packages/dock-blockchain-modules/CHANGELOG.md
- packages/dock-blockchain-modules/package.json
Anoncreds could have credentials without a revealed subject (rare edge case) - this arbitrary check means we cant verify them
> Allow to verify credentials with no revealed subject

- examples/CHANGELOG.md
- examples/package.json
- packages/cheqd-blockchain-api/CHANGELOG.md
- packages/cheqd-blockchain-api/package.json
- packages/cheqd-blockchain-modules/CHANGELOG.md
- packages/cheqd-blockchain-modules/package.json
- packages/credential-sdk/CHANGELOG.md
- packages/credential-sdk/package.json
- packages/credential-sdk/src/vc/schema.js
- packages/dock-blockchain-api/CHANGELOG.md
- packages/dock-blockchain-api/package.json
- packages/dock-blockchain-modules/CHANGELOG.md
- packages/dock-blockchain-modules/package.json
Fixes edge case where subject contains only ID, but schema doesnt mention it/mark as a requirement. In this case subject is empty, which the SDK then thinks is a JSON-LD error. To solve this we remove the ID field after checking for empty compaction
> Fix schema validation with ID only when ID isnt required

- examples/CHANGELOG.md
- examples/package.json
- packages/cheqd-blockchain-api/CHANGELOG.md
- packages/cheqd-blockchain-api/package.json
- packages/cheqd-blockchain-modules/CHANGELOG.md
- packages/cheqd-blockchain-modules/package.json
- packages/credential-sdk/CHANGELOG.md
- packages/credential-sdk/package.json
- packages/credential-sdk/src/vc/verifiable-presentation.js
- packages/dock-blockchain-api/CHANGELOG.md
- packages/dock-blockchain-api/package.json
- packages/dock-blockchain-modules/CHANGELOG.md
- packages/dock-blockchain-modules/package.json
- scripts/migration/CHANGELOG.md
- scripts/migration/package.json
There is also no need to ensure there are no duplicates when adding credentials, caller should have full control.
This was a tricky one to spot as it didn't happen all the time due to using JSON.stringify - but I ran into a case lately where this happened with 3 credentials
> Fix presentation changing credential order
